### ISSUE TITLE
Wiring LEDs up

### ISSUE THREAD

**Issue by aranw** [AsherGlick/Charliecube#1]
Hey didn't know where else to put this as couldn't find a comments box or email address on your site so thought on here would be fine for this question.

Basically in regards to wiring the LEDs up, the diagram shows one line connecting to one pin of the 4 pins per column, is it meant to be one wire per pin so for each column in a group would be 4 wires daisy chained? 

Edit: Also does choosing a wiring group change the way the LEDs react? E.g. group 1 would make LEDs light up in one way but if using group 4 would make LEDs light up in a different order?

**Comment by AsherGlick** [comment]
Each wire is connected to 4 columns. There are 16 wires all together, hence 16 digital pins. I just broke it up into 4 different groups to make it easier to understand when assembling. If you click on the pictures on the website to make them bigger you will see that each wire connects to a different corner of the column. The first group is the lower left, second is the top left, third is the lower right, fourth is the top right.

I hope that answers your question, I will try to make the documentation a bit clearer about that

**Comment by aranw** [comment]
I think I understand better now what you mean, but in regards to images on the website, I can't see any that show all 16 wires like you mention... 

Unless am going blind? 0_o

**Comment by AsherGlick** [comment]
Sorry if it was not clear how to wire up the LEDs to the pins. Each wire connects to 4 spires there are 4 groups of 4 wires. for wires connect to each spire. the connections are denoted by circles on the wiring images on the website. There is no image of all 16 wires together, however as of this afternoon a pinout for the arduino has been given. Thank you for your interest
